name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  deploy-and-attack:
    name: Demonstration of Gremlin Integration Into CICD Pipeline
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.9
        user-repo:
          - booshington/cicd-integration-microservices-demo #replace with your repo
        # state-store:
        #   - cicd-demo-boosh-gremlin-rocks-state-store
        # region:
        #   - us-east-2
        # cluster-name:
        #   - cicd-demo.boosh.gremlin.rocks
        # cluster-id:
        #   - cicd-demo.boosh.gremlin.rocks
        # team-id:
        #   - e071eb40-3f85-42a3-b1eb-403f8512a32d
    steps:
      #redeploys AWS cluster
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ matrix.region }}
      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1
      # - uses: actions-hub/kubectl@master
      #   name: Deploy application
      #   env:
      #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      #   with:
      #     args: get pods
      #     args: apply -f deploy/kubernetes/manifests/00-sock-shop-ns.yaml -f deploy/kubernetes/manifests
      # - uses: webfactory/ssh-agent@v0.5.3
      #   name: 
      #   with:
      #     ssh-private-key: ${{ secrets.CICD_SSH_KEY }}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Retrieve CICD Integrations repo and install
        uses: actions/checkout@master
        with:
          repository: gremlin/gremlin-ci-integrations
          ssh-key: ${{ secrets.CICD_SSH_KEY }}
          path: cicd_cli
      - name: Install CICD Integration CLI
        run: |
          pip3 install -e cicd_cli/engine
          pip3 install pyyaml wrapt gremlinapi
      - name: Retrieve this Microservices repo
        uses: actions/checkout@master 
        with:
          repository: ${{ matrix.user_repo }}
          path: microservices-demo
      - name: Run Gremlin Reliability Experiments
        env:
          GREMLIN_API_KEY: ${{ secrets.GREMLIN_API_KEY }}
        run: |
          gremlinci --yaml microservices-demo/gremlincicd.yaml