name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  deploy-and-attack:
    name: (Re)deploy app and run Gremlin attacks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        state-store:
          - cicd-demo-boosh-gremlin-rocks-state-store
        python-version:
          - 3.9
        region:
          - us-east-2
        cluster-name:
          - cicd-demo.boosh.gremlin.rocks
        cluster-id:
          - cicd-demo.boosh.gremlin.rocks
        team-id:
          - e071eb40-3f85-42a3-b1eb-403f8512a32d
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Deploy application
        run: |
          kubectl create -f deploy/kubernetes/manifests/00-sock-shop-ns.yaml -f deploy/kubernetes/manifests
      - name: Install Gremlin CI CLI
        run: |
          pip3 install gremlin-ci-engine
      - name: Run Gremlin Reliability Experiments
        run: |
          gremlinci --yaml gremlincicd.yaml